name: Python package

on:
  workflow_dispatch:
  schedule:
    - cron: '53,55 20 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run covid numbers
      run: |
        python covid_cases.py
    - name: Commit
      run: |
        git config --global user.email dlhxr@163.com
        git config --global user.name dlhxr
        git add .
        git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
